### ISSUE TITLE
Runtime-Error "unreachable" while parsing xml-file

### ISSUE THREAD

**Issue by cjk** [justinwilaby/sax-wasm#14]
When following the node-example, I'm getting the following error with an arbitrary xml-file:

```
wasm://wasm/0001d47a:9

^

RuntimeError: unreachable
    at wasm-function[8]:1
    at wasm-function[7]:104
    at wasm-function[9]:45
    at wasm-function[12]:3
    at wasm-function[19]:70
    at wasm-function[11]:100
    at wasm-function[37]:1555
    at wasm-function[28]:3662
    at wasm-function[27]:12
    at SAXParser.write (/home/cjk/proj/daimler/iparts/db-builder/node_modules/sax-wasm/lib/saxWasm.js:209:9)
```

**Comment by cjk** [comment]
Hm... probably has to do with the byteLength which exceeds what's in the current chunk sometimes.

But strange some (large) xml-files can be parsed without error, on others it fails - like a 50% chance for my data.

**Comment by justinwilaby** [comment]
Hi @cjk ! Thanks for the submission. Does your xml file contain multi-byte utf-8 chars by chance?

**Comment by cjk** [comment]
@justinwilaby Ah, yes it does - it includes translated content in many languages, like Chinese, Japanese, ... 
That might indeed explain it!

Hope there is solution for those situations?

**Comment by justinwilaby** [comment]
I think I have a fix already. There was a loose end when the chunk included parts of a multi-byte character that I wrapped up. 

If you are able to, clone the repo and checkout `fix/#14-unreachable` then build from source. Copy in the contents of `lib/` to your project's `node_modules/` and retry. If this fixes it, I'll merge and publish. If not, I might need to do some more testing, perhaps with the XML you're seeing this error on.

Also, try using 32k or 16k chunks in the `highWaterMark` option. Then push all the way up to 1024k and see if that is a workaround.

**Comment by cjk** [comment]
Thanks for responding so quickly! I'll see if I can get it to build and report back.
I already tried using smaller chunks, but that didn't seem to help.

**Comment by justinwilaby** [comment]
Great! I made some additional tweaks to the JS side regarding memory. It should fix some related issues with allocations by the WASM process in the middle of a parse operation.

**Comment by cjk** [comment]
OK, applied your changes, rebuilt but the error still happens.
Next I tried to put together a minimal XML-file to reproduce the error. This was not straightforward, since deleting some elements or text can make the error disappear.

Because the content of the sample-xml *could* be considered internal, I can not just post it - hope a PM with an send.firefox.com-link is OK?

**Comment by justinwilaby** [comment]
Ok sounds good. FF send link works! I'll work on this as soon as I can repro.

**Comment by justinwilaby** [comment]
Strange. I'm not able to repro this error. It seems to work even with the current build. I'm testing it by plugging it into [this test](https://github.com/justinwilaby/sax-wasm/blob/master/src/js/__test__/largeXML.spec.js#L45) and running `mocha src/js/__test__/largeXML.spec.js` from the project root. Are you able to confirm that the file is utf-8 encoded?

**Comment by cjk** [comment]
@justinwilaby Ah, maybe I know why you can't reproduce - I changed my chunk-size to 8k in the meantime + totally forgot about it.
Try again with the given file and replace

`const options = { highWaterMark: 64 * 1024 }`

with

`const options = { highWaterMark: 8 * 1024 }`

And see if the error appears.

Sorry for the confusion.

**Comment by cjk** [comment]
BTW it should be UTF-8, the file-utility says `XML 1.0 document, UTF-8 Unicode text`.

**Comment by justinwilaby** [comment]
@cjk - I was finally able to repro this and have a possible solution in the `fix/#14-unreachable` branch. Can you verify the fix? Thank you for your help with all this!

**Comment by cjk** [comment]
Alright, after building + testing against previously failing XML-documents the error is gone - that's great, thanks a lot!
And BTW the speed of the lib is really remarkable, I'm glad you wrote it! :100:

**Comment by justinwilaby** [comment]
@cjk - Excellent. `v1.3.1` with this fix has been published! 
Thanks again for your help. I'm happy to hear the speed of this tool matches the advertising :)
