### ISSUE TITLE
Parser failing on some XML files

### ISSUE THREAD

**Issue by Christilut** [justinwilaby/sax-wasm#21]
Hey, awesome project. I'm trying to create my own XML parser with this since I had to use sax anyway.

I've got it mostly running but on some XML files it's acting weird. It seems to make a Tag out of an Attribute.

The full prototype that I'm using can be found [here](https://github.com/Christilut/rekordcloud-library-parser). Just `npm install` and `npm run dev` should show an error.

If you debug it and inspect the `tag.attributes` then you can see that the first attribute has a name of `file:localhostZ:audioDarude20-2....` which is actually the value of the `Location` attribute.

I thought maybe some weird character is doing this but I couldn't find anything.

Any ideas?

**Comment by justinwilaby** [comment]
Thank you for opening this issue! I'll triage and get an RCA soon. I'm not seeing anything in your XML that stands out. It could be a chunking issue. Have you tried to adjust the `highWaterMark` to something like 64k or 128k?

**Comment by Christilut** [comment]
I just tried and at 512k it starts working correctly. The test file is 1.6MB.

**Comment by justinwilaby** [comment]
This is good info. It shouldn't be hard to track down and fix. Thank you!

**Comment by justinwilaby** [comment]
#22 Fixes this issue. @Christilut - Thank you for catching this!

**Comment by justinwilaby** [comment]
Merged #22 and published v1.4.1 with this fix.
