### ISSUE TITLE
error for XML documents with comments

### ISSUE THREAD

**Issue by russaa** [justinwilaby/sax-wasm#27]
**Describe the bug**

The parser seems to have problems handling comments in XML documents:

the parser does not seem to correctly recognize the comment closing sequence `-->`.

As a result, tags after the comment are not correctly parsed anymore.

**To Reproduce**
1. initialize parser to emit events for `SaxEventType.Attribute | SaxEventType.OpenTag | SaxEventType.Comment`

2. attach an event handler, that prints the tag & attribute & comment information, e.g. something like
```javascript
function eventHandler(event, data) {
  if (event === SaxEventType.OpenTag) {
    // process open tag
    console.log('sax event OpenTag (',event,') -> ', data.name)
    data.attributes.forEach(function(attrData) {
      if(process.env.verbose) console.log('    tag attribute '+attrData.name+'='+JSON.stringify(attrData.value)+' at[', attrData.valueStart, ',', attrData.valueEnd, ']')
    });
  } else if (event === SaxEventType.Attribute) {
    // process attribute
    console.log('sax event Attribute (',event,') -> '+data.name+'='+JSON.stringify(data.value)+' at[', data.valueStart, ',', data.valueEnd, ']')
  } else if (event === SaxEventType.Comment) {
    // process comment tag
    console.log('sax event Comment (',event,') -> ', data.name || data.constructor.name, data.value)
  } else {
    // process unknown tag
    console.log('sax event ',event,' -> ', data.name || data.constructor.name, Buffer.from(data.data).toString('utf8'), data)
  }
};
```

3. parse the XML code
```
<?xml version="1.0" encoding="UTF-8"?>
<plugin name="test 1 attr">

  <name name="test 2 attr">the plugin name</name>

  <!-- name="test 3 attr" some comment -->

  <keywords name="test 4 attr">some,key,words</keywords>

</plugin>
```

**Expected behavior**

The tag `<keywords>` and its attribute `name` should be passed into the event handler.  
Instead the last event that is triggered is for the comment.

When the comment is removed, the XML code is parsed as expected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node.js
 - Version 12.16.3

**Comment by justinwilaby** [comment]
Verified repro steps. Fix is forthcoming.
