### ISSUE TITLE
end positions for attribute names include whitespaces

### ISSUE THREAD

**Issue by russaa** [justinwilaby/sax-wasm#30]
**Describe the bug**

The end position for attribute names `nameEnd` is returned including any trailing whitespaces up until the `=` character.

**To Reproduce**
1. initialize parser to emit events for `SaxEventType.Attribute | SaxEventType.OpenTag`

2. attach an event handler, that prints the tag & attribute information, e.g. something like
```javascript
function eventHandler(event, data) {
  if (event === SaxEventType.OpenTag) {
    // process open tag
    console.log('sax event OpenTag (',event,') -> ', data.name)
    data.attributes.forEach(function(attrData) {
      if(process.env.verbose) console.log('    tag attribute '+attrData.name+'='+JSON.stringify(attrData.value)+' with name at [', attrData.nameStart, ',', attrData.nameEnd, ']')
    });
  } else if (event === SaxEventType.Attribute) {
    // process attribute
    console.log('sax event Attribute (',event,') -> '+data.name+'='+JSON.stringify(data.value)+' with name at [', data.nameStart, ',', data.nameEnd, ']')
  } else {
    // process unknown tag
    console.log('sax event ',event,' -> ', data.name || data.constructor.name, Buffer.from(data.data).toString('utf8'), data)
  }
};
```

3. parse the XML code
```xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin
    version       =   "1.0.0"   >
</plugin>
```

**Expected behavior**

The end position for the name of the `version` attribute should be at `{ line: 2, character: 11 }`.  
Instead the end position currently includes the whitespaces up to the `=` character, i.e. is `{ line: 2, character: 18 }`.

This could maybe fixed in [`parser.rs::attribute_name()`](https://github.com/justinwilaby/sax-wasm/blob/master/src/sax/parser.rs#L478) when handling
the `is_whitespace(grapheme)` case, by only updating `self.attribute.name_end` when the `self.state` is not already `State::AttribNameSawWhite`.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node.js
 - Version 12.16.3

**Comment by justinwilaby** [comment]
@russaa - Good catch! 

I'll get this repro up locally and test. It should be a fairly easy fix using the strategy you pointed out.
