### ISSUE TITLE
Playground.js not working

### ISSUE THREAD

**Issue by naman03malhotra** [justinwilaby/sax-wasm#32]
In playground.js the external method event_listener is not being triggered by the parser.

```js
function event_listener(event, ptr, len) {
    console.log('here');
    const linearMemory = result.instance.exports.memory;
    const memBuff = Buffer.from(linearMemory.buffer, ptr, len);
    const rawString = memBuff.toString();
    console.log(event, rawString);
    try {
      JSON.parse(rawString);
    } catch (e) {
      debugger;
    }
  }

```

`here` is never logged.

**Comment by justinwilaby** [comment]
@naman03malhotra - Thanks for the heads up! Looks like the memory buffer is getting detached after instantiating the parser. This should be a quick fix. 

Note that the `playground.js` is used mainly as a low-level utility to view the raw encoded output from the parser and represents the absolute minimal amount of code to parse something. Its output isn't useful until it is decoded by `SAXParser.eventTrap`

**Comment by naman03malhotra** [comment]
@justinwilaby thanks for the quick response.
