### ISSUE TITLE
Problem with a repeated fragment on a large xml file

### ISSUE THREAD

**Issue by Avol-V** [justinwilaby/sax-wasm#36]
When parsing a large XML file, at some point a certain fragment (but not the first one) starts repeating itself instead of the original content. Increasing the highWaterMark value increases the repeated fragment.

I just took the Node-example and changed this part:
```js
const parser = new SAXParser(SaxEventType.Text, options);
parser.eventHandler = (event, data) => {
  if ( data.value.includes( 'CHAPTER' ) ) {
    console.log(data.value);
  }
};
```

`CHAPTER` is some text that is repeated periodically with a variable part (a number).

The output looks like this:
```
CHAPTER ONE
CHAPTER TWO
CHAPTER THREE
CHAPTER TWO
CHAPTER THREE
CHAPTER TWO
CHAPTER THREE
...
```

Should be like:
```
CHAPTER ONE
CHAPTER TWO
CHAPTER THREE
CHAPTER FOUR
CHAPTER FIVE
CHAPTER SIX
CHAPTER SEVEN
...
```

Node v12.18.0

**Comment by justinwilaby** [comment]
@Avol-V - Do you have a sample XML file I can use to repro this?

**Comment by Avol-V** [comment]
It's a minimal case that I can create — https://yadi.sk/d/YDbyNLZXOIy0eg
Any change in content, that change size in bytes (including unicode characters), can change output in different ways, including no output at all. So I just replace all characters to create file, that I can upload and publish.

Current output is:
```
БББББ ААААА-1
БББББ ААААА-2
БББББ ААААА-3
БББББ ААААА-2
```

Should be:
```
БББББ ААААА-1
БББББ ААААА-2
БББББ ААААА-3
БББББ ААААА-4
```

**Comment by justinwilaby** [comment]
@Avol-V - Can you please confirm that #37 fixes this issue? This was a good catch, thank you.

**Comment by Avol-V** [comment]
Yes, it fixed! Thanks!
