### ISSUE TITLE
No changelog?

### ISSUE THREAD

**Issue by daKmoR** [justinwilaby/sax-wasm#40]
I am using `sax-wasm@^1.4.5` and I would like to update to 2.x and for that, I usually check the changelog but I seem to can't find one here 🤔

Is it missing? what user-facing API changed from 1.x to 2.x?

**Comment by Siemienik** [comment]
The Compare tool provides really clear information about chagelog:
https://github.com/justinwilaby/sax-wasm/compare/v1.4.5...v2.0.0

Megred PRs:
https://github.com/justinwilaby/sax-wasm/pull/37 (v1.4.6)
https://github.com/justinwilaby/sax-wasm/pull/38 (v2 with breaking changes description)

**Comment by daKmoR** [comment]
thx 🤗
