### ISSUE TITLE
way to identify JSX style attributes

### ISSUE THREAD

**Issue by samuelcolvin** [justinwilaby/sax-wasm#45]
Hi, sorry me again. 

I can parse the following and it works just fine: `<div class={foobar}/>`.

However, there's no way to differentiate the attribute value from `<div class="foobar"/>`.

`Attribute.value` is just a `Text`:

https://github.com/justinwilaby/sax-wasm/blob/abd01fca740b87a7989cdc788216db5aa81ec030/src/sax/tag.rs#L110-L113

If there was some way to flag the difference it would be really useful for my application.

**Comment by justinwilaby** [comment]
This is a great idea. It should be fairly easy to add an `attributeType` field to the `Attribute` class for this use case. Angular template bindings on attribute names `[()]` might be a bit trickier. 

I'm working on a new approach to shuffling memory in the wasm that should get the benchmarks from 90ms down to 20-40ms. I'll cover your use case as a one-off then look at incorporating the Angular attr binding types in the new version. 

I should be able to get to this Mon or Tues (June 1st or 2nd)

**Comment by samuelcolvin** [comment]
That's amazing, thank you.

**Comment by samuelcolvin** [comment]
The speedups sound great too.

I'm building a templating language which roughly follows JSX syntax but doesn't generate JS or require `eval()` (in this regard it's a bit like mustache and liquid).

I mostly want to use the templates on cloudflare workers, which have relatively strict CPU limits.

Parsing the template for the first time is the slowest bit and sometimes hits the CPU limit, hence why I switched to sax-wasm and care about speed.

**Comment by samuelcolvin** [comment]
https://github.com/samuelcolvin/yatl  - very much a WIP, but you can see the basics working in tests.
