### ISSUE TITLE
React native npm module request $$

### ISSUE THREAD

**Issue by dataforce-troy** [justinwilaby/sax-wasm#72]
Hi Justin
I'm wondering if you would be nterested to develop a react native npm module based on your sax-wasm project. 

Happy to pay for this service.

To give some background, we currently have an iOS app written in React Native that was ported from a java Android app. A lot of the code was converted to Kotlin, and then we compile the kotlin down to javascript. The application generally works, but there's a key performance bottleneck around the parsing of XML. It currently uses a Kotlin version of XMLPullParser, but we would like to replace it with something significantly better. Hence, the desire for a fast native (Rust/C++) XML parser but staying with the event-driven parsing style.

The ability to make a web request (POST/GET) within the native code is a bonus, but not necessary. Given the built in XMLHttpRequest object in react native only sends incremental updates in text mode, SaxParser.write() will need to support string input as well as uint8array. We'll also be reading files from the filesystem.

We intend to include this project into our main application as a NPM dependency.

Please response if you are interested and I will supply my contact details and more details on the project.

**Comment by justinwilaby** [comment]
Closing this. Not enough interest from the community to pursue.
