### ISSUE TITLE
Use WebAssembly.instantiateStreaming

### ISSUE THREAD

**Issue by wrnrlr** [justinwilaby/sax-wasm#76]
Using `WebAssembly.instantiateStreaming` instead of `WebAssembly.instantiate` will improve loading time because the wasm is read directly from a stream without being copied to a ArrayBuffer first.

This method expects a `Response` or a `Promise<Response>` so I think the most straightforward way to enable this is to check for this types in `SAXParser.prepareWasm` and call `WebAssembly.instantiateStreaming` otherwise fall back the the old `WebAssembly.instantiate`

**Comment by justinwilaby** [comment]
Good call. Implementing....
