### ISSUE TITLE
Improve API ergonomics by add parse() method to SAXParser

### ISSUE THREAD

**Issue by wrnrlr** [justinwilaby/sax-wasm#79]
The API can be improved by adding a simple generator function like so:

```js
class SAXParser {
  async *parse(reader) {
    let event
    this.eventHandler = function() {event=arguments}
    while(true) {
      const chunk = await reader.read()
      if (chunk.done) return this.end()
      this.write(chunk.value)
      if (event) {yield event;event=null}
    }
  }
}
```

No more need to write the callback and while loop yourself, the code becomes a lot more straightforward while adding little overhead.

```js
for await (const [event,data] of parser.parse(reader))
    console.log({event,data})
```

I am currently already doing something like this using a wrapper:

```js
async function SaxParser(events, options) {
  const parser = new SAXParser(events, options),
    saxWasmResponse = await loadSaxWasm()
  await parser.prepareWasm(saxWasmResponse)
  return async function*(reader) {
    let event
    parser.eventHandler = function() {event=arguments}
    while(true) {
      const chunk = await reader.read()
      if (chunk.done) return parser.end()
      parser.write(chunk.value)
      if (event) {yield event;event=null}
    }
  }
}
```

Love to know what you think.

**Comment by justinwilaby** [comment]
I do like the idea. I would like to explore taking it to the next step and defining an iterator which can then be used in a for..await.. loop.

```
class SaxIterator {
  reader;
  parser;
  accumulator = [];

  constructor(readable, events, options) {
    this.readable = readable;
    this.parser = new SAXParser(events, options);
    this.parser.eventHandler = (type, detail) => this.accumulator(detail);
  }

  [Symbol.asyncIterator]() {
     return this.iterateFromOffset(0);
  }

  async *iterateFromOffset(offset) {
    // Eager piping of parser output to generator
    for await (const chunk of this.readable) {
      this.parser.write(chunk);
      if (accumulator[offset]) {
        yield accumulator[offset];
        offset ++;
      }
    }

    // Parsing completed but the accumulator still has items to yield.
    while(accumulator[offset]) {
       yield accumulator[offset];
       offset ++;
    }
  }
}
```

**Comment by justinwilaby** [comment]
This mechanism does need updating since it was originally written 4 years ago.

**Comment by wrnrlr** [comment]
That sounds interesting, I've just started to learn about iterators and generators in js. What is the benefit for of using the full iterator here? So the producer and consumer can react independently on events? You are correct that in my original code there is a bug where there is a chance that final event is not emitted, but this can be fixed by putting the yield statement at the beginning of the loop. Does your current implementation not have the problem that it hold on to all event data.

**Comment by wrnrlr** [comment]
ok, I get it now you always need the accumulator because there can be more then just one event left to process

**Comment by justinwilaby** [comment]
The above example omits the event for brevity. The final implementation would store a tuple in the accumulator with the event/detail pair from each node encountered. With the iterator solution, it is possible to pass around the `SaxIterator` instance to consumers that may iterate it at an unknown time while performing the parsing only once. 


Also, it is possible to extend `Array` and access indices directly, provided the parsed document has reached a node at the specified index. e.g.

```ts
class SaxIterator extends Array {
  // ...
}
const saxIterator = new SaxIterator(readable, events, options);
console.log(await saxIterator[3]); // Logs the 3rd node encountered by the parser.
```

**Comment by wrnrlr** [comment]
That is an interesting solution, but for my use case I have more then a terrabyte of xml to parse and I would prefer not to keep anything around I don't need. My current solution extends to TransformStream to read in a chunks of bytes and writes elements. This solution can be combined with an xpath like technology to search for multiple kinds of elements in parallel. If one does desire to elements to be cached then this can be done with a straightforward `CachedTransformStream`.

The current implementation looks something like this:

```js
let SAX_WASM
async function loadSaxWasm() {
  if (!SAX_WASM) SAX_WASM = Deno.readFileSync('./util/sax.wasm')
  return SAX_WASM
}

export class SaxDecoderStream extends TransformStream {
  constructor(parser) {
    super()
    const readable = super.readable
      .pipeThrough(new TransformStream({
        async transform(chunk, controller) {
          parser.eventHandler = (type,data) => controller.enqueue({type, data})
          parser.write(chunk)
        },
        flush() {parser.end()}
      }));
    Object.defineProperty(this, 'readable', {get() {return readable}})
  }
  static async create(events, options) {
    const parser = new SAXParser(events, options)
    await parser.prepareWasm(await loadSaxWasm())
    return new SaxDecoderStream(parser)
  }
}

async function saxDecoderFromReadable(readable) {
  const stream = await SaxDecoderStream.create(SaxEventType.OpenTagStart|SaxEventType.CloseTag|SaxEventType.Attribute|SaxEventType.Text);
  (async ()=> {
    let writer = stream.writable.getWriter();
    let reader = readable.getReader();
    while(true) {
      const chunk = await reader.read();
      if (chunk.done) return writer.close()
      await writer.write(chunk.value);
    }
  })().catch(e=>{console.error(e)})
  return stream.readable
}

const bookstore = `<?xml version="1.0" encoding="UTF-8"?>
  <bookstore>
    <book><title lang="en">Harry Potter</title><price>29.99</price></book>
    <book><title lang="en">Learning XML</title><price>39.95</price></book>
    <book><title lang="nl">The Prince</title><price test="1">50.00</price></book>
  </bookstore>`
const readable = stringToStream(bookstore),
  iterator = await saxDecoderFromReadable(readable)
for await (const e of iterator) {
  console.log(e)
}
```
