### ISSUE TITLE
Error with JSX parsing of inline valid javascript expressions including `<`

### ISSUE THREAD

**Issue by marcusglowe** [justinwilaby/sax-wasm#81]
**Describe the bug**
Suppose you have the following:
```jsx
<foo>{bar < baz ? <div></div> : <></>}</foo>
```

The SAX parser will detect that `<baz ? <div>` is a tag
**To Reproduce**
Use this example

**Expected behavior**
I expect that any complex expression is ignored from the parser, even if it contains `<`

I'd be happy to help fix if there are code pointers / strategies that would be effective in solving this!

**Comment by justinwilaby** [comment]
I have been able to confirm this defect. Nice catch!

I would expect the parser to report any nodes that exist in the jsx expression. This might be quite the rabbit hole however. I'll explore some options soon and report back.
