### ISSUE TITLE
Locate sax-wasm.wasm automatically

### ISSUE THREAD

**Issue by wrnrlr** [justinwilaby/sax-wasm#83]
You could do something like this where you locate the wasm file based on `import.meta.resolve`. This should work for local files also, at least if fetch supports this. Dunno if this works on Node though:

```
parser.prepareWasm(fetch(import.meta.resolve('./sax.wasm')))
```

**Comment by justinwilaby** [comment]
Seems like this could be an update to the readme.md

**Comment by justinwilaby** [comment]
#92 provides this functionality. Syntax is:

```
const wasmUrl = new URL(import.meta.resolve('sax-wasm/lib/sax-wasm.wasm'));
const saxWasm = await readFile(wasmUrl);

const parser = new SAXParser(SaxEventType.CloseTag);
await parser.prepareWasm(saxWasm);
```
